Make sure that PREEMPTIBLE is unset appropriately
The current configuration in the .env.example file has PREEMPTIBLE=false, this is not handled and leads to a failure during the cluster creation:
ERROR: (gcloud.container.clusters.create) unrecognized arguments: false

This value needs to be either set to --preemptible (which was already handled) or removed, which is this modification.
Tested using the cloud shell tools.